/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as CoaRouteImport } from './routes/coa'
import { Route as CatatKegiatanRouteImport } from './routes/catat-kegiatan'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as LaporanNeracaPusatRouteImport } from './routes/laporan.neraca-pusat'
import { Route as LaporanNeracaKonsolidasiRouteImport } from './routes/laporan.neraca-konsolidasi'
import { Route as LaporanLabaRugiRouteImport } from './routes/laporan.laba-rugi'
import { Route as LaporanBagiHasilRouteImport } from './routes/laporan.bagi-hasil'

const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaRoute = CoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const CatatKegiatanRoute = CatatKegiatanRouteImport.update({
  id: '/catat-kegiatan',
  path: '/catat-kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LaporanNeracaPusatRoute = LaporanNeracaPusatRouteImport.update({
  id: '/laporan/neraca-pusat',
  path: '/laporan/neraca-pusat',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanNeracaKonsolidasiRoute =
  LaporanNeracaKonsolidasiRouteImport.update({
    id: '/laporan/neraca-konsolidasi',
    path: '/laporan/neraca-konsolidasi',
    getParentRoute: () => rootRouteImport,
  } as any)
const LaporanLabaRugiRoute = LaporanLabaRugiRouteImport.update({
  id: '/laporan/laba-rugi',
  path: '/laporan/laba-rugi',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanBagiHasilRoute = LaporanBagiHasilRouteImport.update({
  id: '/laporan/bagi-hasil',
  path: '/laporan/bagi-hasil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/catat-kegiatan': typeof CatatKegiatanRoute
  '/coa': typeof CoaRoute
  '/pengaturan': typeof PengaturanRoute
  '/laporan/bagi-hasil': typeof LaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof LaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof LaporanNeracaPusatRoute
}
export interface FileRoutesByTo {
  '/catat-kegiatan': typeof CatatKegiatanRoute
  '/coa': typeof CoaRoute
  '/pengaturan': typeof PengaturanRoute
  '/laporan/bagi-hasil': typeof LaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof LaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof LaporanNeracaPusatRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/catat-kegiatan': typeof CatatKegiatanRoute
  '/coa': typeof CoaRoute
  '/pengaturan': typeof PengaturanRoute
  '/laporan/bagi-hasil': typeof LaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof LaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof LaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof LaporanNeracaPusatRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catat-kegiatan'
    | '/coa'
    | '/pengaturan'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catat-kegiatan'
    | '/coa'
    | '/pengaturan'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/catat-kegiatan'
    | '/coa'
    | '/pengaturan'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  CatatKegiatanRoute: typeof CatatKegiatanRoute
  CoaRoute: typeof CoaRoute
  PengaturanRoute: typeof PengaturanRoute
  LaporanBagiHasilRoute: typeof LaporanBagiHasilRoute
  LaporanLabaRugiRoute: typeof LaporanLabaRugiRoute
  LaporanNeracaKonsolidasiRoute: typeof LaporanNeracaKonsolidasiRoute
  LaporanNeracaPusatRoute: typeof LaporanNeracaPusatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa': {
      id: '/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof CoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catat-kegiatan': {
      id: '/catat-kegiatan'
      path: '/catat-kegiatan'
      fullPath: '/catat-kegiatan'
      preLoaderRoute: typeof CatatKegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/laporan/neraca-pusat': {
      id: '/laporan/neraca-pusat'
      path: '/laporan/neraca-pusat'
      fullPath: '/laporan/neraca-pusat'
      preLoaderRoute: typeof LaporanNeracaPusatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/neraca-konsolidasi': {
      id: '/laporan/neraca-konsolidasi'
      path: '/laporan/neraca-konsolidasi'
      fullPath: '/laporan/neraca-konsolidasi'
      preLoaderRoute: typeof LaporanNeracaKonsolidasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/laba-rugi': {
      id: '/laporan/laba-rugi'
      path: '/laporan/laba-rugi'
      fullPath: '/laporan/laba-rugi'
      preLoaderRoute: typeof LaporanLabaRugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/bagi-hasil': {
      id: '/laporan/bagi-hasil'
      path: '/laporan/bagi-hasil'
      fullPath: '/laporan/bagi-hasil'
      preLoaderRoute: typeof LaporanBagiHasilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  CatatKegiatanRoute: CatatKegiatanRoute,
  CoaRoute: CoaRoute,
  PengaturanRoute: PengaturanRoute,
  LaporanBagiHasilRoute: LaporanBagiHasilRoute,
  LaporanLabaRugiRoute: LaporanLabaRugiRoute,
  LaporanNeracaKonsolidasiRoute: LaporanNeracaKonsolidasiRoute,
  LaporanNeracaPusatRoute: LaporanNeracaPusatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
