/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppUspRouteImport } from './routes/_app.usp'
import { Route as AppTransferAntarEntitasRouteImport } from './routes/_app.transfer-antar-entitas'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppCoaRouteImport } from './routes/_app.coa'
import { Route as AppCatatKegiatanRouteImport } from './routes/_app.catat-kegiatan'
import { Route as AppUspIndexRouteImport } from './routes/_app.usp.index'
import { Route as AppUspTransferRouteImport } from './routes/_app.usp.transfer'
import { Route as AppUspPinjamanRouteImport } from './routes/_app.usp.pinjaman'
import { Route as AppUspLaporanRouteImport } from './routes/_app.usp.laporan'
import { Route as AppUspKegiatanRouteImport } from './routes/_app.usp.kegiatan'
import { Route as AppLaporanRekonsiliasiRkRouteImport } from './routes/_app.laporan.rekonsiliasi-rk'
import { Route as AppLaporanNeracaPusatRouteImport } from './routes/_app.laporan.neraca-pusat'
import { Route as AppLaporanNeracaKonsolidasiRouteImport } from './routes/_app.laporan.neraca-konsolidasi'
import { Route as AppLaporanLabaRugiRouteImport } from './routes/_app.laporan.laba-rugi'
import { Route as AppLaporanBagiHasilRouteImport } from './routes/_app.laporan.bagi-hasil'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUspRoute = AppUspRouteImport.update({
  id: '/usp',
  path: '/usp',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferAntarEntitasRoute = AppTransferAntarEntitasRouteImport.update({
  id: '/transfer-antar-entitas',
  path: '/transfer-antar-entitas',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppCoaRoute = AppCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => AppRoute,
} as any)
const AppCatatKegiatanRoute = AppCatatKegiatanRouteImport.update({
  id: '/catat-kegiatan',
  path: '/catat-kegiatan',
  getParentRoute: () => AppRoute,
} as any)
const AppUspIndexRoute = AppUspIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspTransferRoute = AppUspTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspPinjamanRoute = AppUspPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspLaporanRoute = AppUspLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspKegiatanRoute = AppUspKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AppUspRoute,
} as any)
const AppLaporanRekonsiliasiRkRoute =
  AppLaporanRekonsiliasiRkRouteImport.update({
    id: '/laporan/rekonsiliasi-rk',
    path: '/laporan/rekonsiliasi-rk',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanNeracaPusatRoute = AppLaporanNeracaPusatRouteImport.update({
  id: '/laporan/neraca-pusat',
  path: '/laporan/neraca-pusat',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanNeracaKonsolidasiRoute =
  AppLaporanNeracaKonsolidasiRouteImport.update({
    id: '/laporan/neraca-konsolidasi',
    path: '/laporan/neraca-konsolidasi',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanLabaRugiRoute = AppLaporanLabaRugiRouteImport.update({
  id: '/laporan/laba-rugi',
  path: '/laporan/laba-rugi',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanBagiHasilRoute = AppLaporanBagiHasilRouteImport.update({
  id: '/laporan/bagi-hasil',
  path: '/laporan/bagi-hasil',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/coa': typeof AppCoaRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/usp': typeof AppUspRouteWithChildren
  '/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/usp/kegiatan': typeof AppUspKegiatanRoute
  '/usp/laporan': typeof AppUspLaporanRoute
  '/usp/pinjaman': typeof AppUspPinjamanRoute
  '/usp/transfer': typeof AppUspTransferRoute
  '/usp/': typeof AppUspIndexRoute
}
export interface FileRoutesByTo {
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/coa': typeof AppCoaRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/': typeof AppIndexRoute
  '/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/usp/kegiatan': typeof AppUspKegiatanRoute
  '/usp/laporan': typeof AppUspLaporanRoute
  '/usp/pinjaman': typeof AppUspPinjamanRoute
  '/usp/transfer': typeof AppUspTransferRoute
  '/usp': typeof AppUspIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/_app/coa': typeof AppCoaRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/_app/usp': typeof AppUspRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/_app/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/_app/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/_app/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/_app/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/_app/usp/kegiatan': typeof AppUspKegiatanRoute
  '/_app/usp/laporan': typeof AppUspLaporanRoute
  '/_app/usp/pinjaman': typeof AppUspPinjamanRoute
  '/_app/usp/transfer': typeof AppUspTransferRoute
  '/_app/usp/': typeof AppUspIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catat-kegiatan'
    | '/coa'
    | '/pengaturan'
    | '/transfer-antar-entitas'
    | '/usp'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/laporan/rekonsiliasi-rk'
    | '/usp/kegiatan'
    | '/usp/laporan'
    | '/usp/pinjaman'
    | '/usp/transfer'
    | '/usp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/catat-kegiatan'
    | '/coa'
    | '/pengaturan'
    | '/transfer-antar-entitas'
    | '/'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/laporan/rekonsiliasi-rk'
    | '/usp/kegiatan'
    | '/usp/laporan'
    | '/usp/pinjaman'
    | '/usp/transfer'
    | '/usp'
  id:
    | '__root__'
    | '/_app'
    | '/_app/catat-kegiatan'
    | '/_app/coa'
    | '/_app/pengaturan'
    | '/_app/transfer-antar-entitas'
    | '/_app/usp'
    | '/_app/'
    | '/_app/laporan/bagi-hasil'
    | '/_app/laporan/laba-rugi'
    | '/_app/laporan/neraca-konsolidasi'
    | '/_app/laporan/neraca-pusat'
    | '/_app/laporan/rekonsiliasi-rk'
    | '/_app/usp/kegiatan'
    | '/_app/usp/laporan'
    | '/_app/usp/pinjaman'
    | '/_app/usp/transfer'
    | '/_app/usp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usp': {
      id: '/_app/usp'
      path: '/usp'
      fullPath: '/usp'
      preLoaderRoute: typeof AppUspRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer-antar-entitas': {
      id: '/_app/transfer-antar-entitas'
      path: '/transfer-antar-entitas'
      fullPath: '/transfer-antar-entitas'
      preLoaderRoute: typeof AppTransferAntarEntitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coa': {
      id: '/_app/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof AppCoaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catat-kegiatan': {
      id: '/_app/catat-kegiatan'
      path: '/catat-kegiatan'
      fullPath: '/catat-kegiatan'
      preLoaderRoute: typeof AppCatatKegiatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usp/': {
      id: '/_app/usp/'
      path: '/'
      fullPath: '/usp/'
      preLoaderRoute: typeof AppUspIndexRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/transfer': {
      id: '/_app/usp/transfer'
      path: '/transfer'
      fullPath: '/usp/transfer'
      preLoaderRoute: typeof AppUspTransferRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/pinjaman': {
      id: '/_app/usp/pinjaman'
      path: '/pinjaman'
      fullPath: '/usp/pinjaman'
      preLoaderRoute: typeof AppUspPinjamanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/laporan': {
      id: '/_app/usp/laporan'
      path: '/laporan'
      fullPath: '/usp/laporan'
      preLoaderRoute: typeof AppUspLaporanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/kegiatan': {
      id: '/_app/usp/kegiatan'
      path: '/kegiatan'
      fullPath: '/usp/kegiatan'
      preLoaderRoute: typeof AppUspKegiatanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/laporan/rekonsiliasi-rk': {
      id: '/_app/laporan/rekonsiliasi-rk'
      path: '/laporan/rekonsiliasi-rk'
      fullPath: '/laporan/rekonsiliasi-rk'
      preLoaderRoute: typeof AppLaporanRekonsiliasiRkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/neraca-pusat': {
      id: '/_app/laporan/neraca-pusat'
      path: '/laporan/neraca-pusat'
      fullPath: '/laporan/neraca-pusat'
      preLoaderRoute: typeof AppLaporanNeracaPusatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/neraca-konsolidasi': {
      id: '/_app/laporan/neraca-konsolidasi'
      path: '/laporan/neraca-konsolidasi'
      fullPath: '/laporan/neraca-konsolidasi'
      preLoaderRoute: typeof AppLaporanNeracaKonsolidasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/laba-rugi': {
      id: '/_app/laporan/laba-rugi'
      path: '/laporan/laba-rugi'
      fullPath: '/laporan/laba-rugi'
      preLoaderRoute: typeof AppLaporanLabaRugiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/bagi-hasil': {
      id: '/_app/laporan/bagi-hasil'
      path: '/laporan/bagi-hasil'
      fullPath: '/laporan/bagi-hasil'
      preLoaderRoute: typeof AppLaporanBagiHasilRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppUspRouteChildren {
  AppUspKegiatanRoute: typeof AppUspKegiatanRoute
  AppUspLaporanRoute: typeof AppUspLaporanRoute
  AppUspPinjamanRoute: typeof AppUspPinjamanRoute
  AppUspTransferRoute: typeof AppUspTransferRoute
  AppUspIndexRoute: typeof AppUspIndexRoute
}

const AppUspRouteChildren: AppUspRouteChildren = {
  AppUspKegiatanRoute: AppUspKegiatanRoute,
  AppUspLaporanRoute: AppUspLaporanRoute,
  AppUspPinjamanRoute: AppUspPinjamanRoute,
  AppUspTransferRoute: AppUspTransferRoute,
  AppUspIndexRoute: AppUspIndexRoute,
}

const AppUspRouteWithChildren =
  AppUspRoute._addFileChildren(AppUspRouteChildren)

interface AppRouteChildren {
  AppCatatKegiatanRoute: typeof AppCatatKegiatanRoute
  AppCoaRoute: typeof AppCoaRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppTransferAntarEntitasRoute: typeof AppTransferAntarEntitasRoute
  AppUspRoute: typeof AppUspRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLaporanBagiHasilRoute: typeof AppLaporanBagiHasilRoute
  AppLaporanLabaRugiRoute: typeof AppLaporanLabaRugiRoute
  AppLaporanNeracaKonsolidasiRoute: typeof AppLaporanNeracaKonsolidasiRoute
  AppLaporanNeracaPusatRoute: typeof AppLaporanNeracaPusatRoute
  AppLaporanRekonsiliasiRkRoute: typeof AppLaporanRekonsiliasiRkRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatatKegiatanRoute: AppCatatKegiatanRoute,
  AppCoaRoute: AppCoaRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppTransferAntarEntitasRoute: AppTransferAntarEntitasRoute,
  AppUspRoute: AppUspRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLaporanBagiHasilRoute: AppLaporanBagiHasilRoute,
  AppLaporanLabaRugiRoute: AppLaporanLabaRugiRoute,
  AppLaporanNeracaKonsolidasiRoute: AppLaporanNeracaKonsolidasiRoute,
  AppLaporanNeracaPusatRoute: AppLaporanNeracaPusatRoute,
  AppLaporanRekonsiliasiRkRoute: AppLaporanRekonsiliasiRkRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
