/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as LoginUnitRouteImport } from './routes/login.$unit'
import { Route as AppUspRouteImport } from './routes/_app.usp'
import { Route as AppTransferAntarEntitasRouteImport } from './routes/_app.transfer-antar-entitas'
import { Route as AppPengaturanRouteImport } from './routes/_app.pengaturan'
import { Route as AppCoaRouteImport } from './routes/_app.coa'
import { Route as AppCatatKegiatanRouteImport } from './routes/_app.catat-kegiatan'
import { Route as AppUspIndexRouteImport } from './routes/_app.usp.index'
import { Route as AppPengaturanIndexRouteImport } from './routes/_app.pengaturan.index'
import { Route as AppUspTransferRouteImport } from './routes/_app.usp.transfer'
import { Route as AppUspPinjamanRouteImport } from './routes/_app.usp.pinjaman'
import { Route as AppUspLaporanRouteImport } from './routes/_app.usp.laporan'
import { Route as AppUspKegiatanRouteImport } from './routes/_app.usp.kegiatan'
import { Route as AppPusatKegiatanRouteImport } from './routes/_app.pusat.kegiatan'
import { Route as AppPengaturanUsersRouteImport } from './routes/_app.pengaturan.users'
import { Route as AppLaporanRekonsiliasiRkRouteImport } from './routes/_app.laporan.rekonsiliasi-rk'
import { Route as AppLaporanNeracaPusatRouteImport } from './routes/_app.laporan.neraca-pusat'
import { Route as AppLaporanNeracaKonsolidasiRouteImport } from './routes/_app.laporan.neraca-konsolidasi'
import { Route as AppLaporanLabaRugiRouteImport } from './routes/_app.laporan.laba-rugi'
import { Route as AppLaporanBagiHasilRouteImport } from './routes/_app.laporan.bagi-hasil'
import { Route as AppUspLaporanIndexRouteImport } from './routes/_app.usp.laporan.index'
import { Route as AppUspLaporanRekonsiliasiRkRouteImport } from './routes/_app.usp.laporan.rekonsiliasi-rk'
import { Route as AppUspLaporanNeracaRouteImport } from './routes/_app.usp.laporan.neraca'
import { Route as AppUspLaporanLabaRugiRouteImport } from './routes/_app.usp.laporan.laba-rugi'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LoginUnitRoute = LoginUnitRouteImport.update({
  id: '/$unit',
  path: '/$unit',
  getParentRoute: () => LoginRoute,
} as any)
const AppUspRoute = AppUspRouteImport.update({
  id: '/usp',
  path: '/usp',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferAntarEntitasRoute = AppTransferAntarEntitasRouteImport.update({
  id: '/transfer-antar-entitas',
  path: '/transfer-antar-entitas',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppCoaRoute = AppCoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => AppRoute,
} as any)
const AppCatatKegiatanRoute = AppCatatKegiatanRouteImport.update({
  id: '/catat-kegiatan',
  path: '/catat-kegiatan',
  getParentRoute: () => AppRoute,
} as any)
const AppUspIndexRoute = AppUspIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUspRoute,
} as any)
const AppPengaturanIndexRoute = AppPengaturanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPengaturanRoute,
} as any)
const AppUspTransferRoute = AppUspTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspPinjamanRoute = AppUspPinjamanRouteImport.update({
  id: '/pinjaman',
  path: '/pinjaman',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspLaporanRoute = AppUspLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AppUspRoute,
} as any)
const AppUspKegiatanRoute = AppUspKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AppUspRoute,
} as any)
const AppPusatKegiatanRoute = AppPusatKegiatanRouteImport.update({
  id: '/pusat/kegiatan',
  path: '/pusat/kegiatan',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanUsersRoute = AppPengaturanUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppPengaturanRoute,
} as any)
const AppLaporanRekonsiliasiRkRoute =
  AppLaporanRekonsiliasiRkRouteImport.update({
    id: '/laporan/rekonsiliasi-rk',
    path: '/laporan/rekonsiliasi-rk',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanNeracaPusatRoute = AppLaporanNeracaPusatRouteImport.update({
  id: '/laporan/neraca-pusat',
  path: '/laporan/neraca-pusat',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanNeracaKonsolidasiRoute =
  AppLaporanNeracaKonsolidasiRouteImport.update({
    id: '/laporan/neraca-konsolidasi',
    path: '/laporan/neraca-konsolidasi',
    getParentRoute: () => AppRoute,
  } as any)
const AppLaporanLabaRugiRoute = AppLaporanLabaRugiRouteImport.update({
  id: '/laporan/laba-rugi',
  path: '/laporan/laba-rugi',
  getParentRoute: () => AppRoute,
} as any)
const AppLaporanBagiHasilRoute = AppLaporanBagiHasilRouteImport.update({
  id: '/laporan/bagi-hasil',
  path: '/laporan/bagi-hasil',
  getParentRoute: () => AppRoute,
} as any)
const AppUspLaporanIndexRoute = AppUspLaporanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspLaporanRekonsiliasiRkRoute =
  AppUspLaporanRekonsiliasiRkRouteImport.update({
    id: '/rekonsiliasi-rk',
    path: '/rekonsiliasi-rk',
    getParentRoute: () => AppUspLaporanRoute,
  } as any)
const AppUspLaporanNeracaRoute = AppUspLaporanNeracaRouteImport.update({
  id: '/neraca',
  path: '/neraca',
  getParentRoute: () => AppUspLaporanRoute,
} as any)
const AppUspLaporanLabaRugiRoute = AppUspLaporanLabaRugiRouteImport.update({
  id: '/laba-rugi',
  path: '/laba-rugi',
  getParentRoute: () => AppUspLaporanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/coa': typeof AppCoaRoute
  '/pengaturan': typeof AppPengaturanRouteWithChildren
  '/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/usp': typeof AppUspRouteWithChildren
  '/login/$unit': typeof LoginUnitRoute
  '/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/pengaturan/users': typeof AppPengaturanUsersRoute
  '/pusat/kegiatan': typeof AppPusatKegiatanRoute
  '/usp/kegiatan': typeof AppUspKegiatanRoute
  '/usp/laporan': typeof AppUspLaporanRouteWithChildren
  '/usp/pinjaman': typeof AppUspPinjamanRoute
  '/usp/transfer': typeof AppUspTransferRoute
  '/pengaturan/': typeof AppPengaturanIndexRoute
  '/usp/': typeof AppUspIndexRoute
  '/usp/laporan/laba-rugi': typeof AppUspLaporanLabaRugiRoute
  '/usp/laporan/neraca': typeof AppUspLaporanNeracaRoute
  '/usp/laporan/rekonsiliasi-rk': typeof AppUspLaporanRekonsiliasiRkRoute
  '/usp/laporan/': typeof AppUspLaporanIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteWithChildren
  '/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/coa': typeof AppCoaRoute
  '/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/login/$unit': typeof LoginUnitRoute
  '/': typeof AppIndexRoute
  '/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/pengaturan/users': typeof AppPengaturanUsersRoute
  '/pusat/kegiatan': typeof AppPusatKegiatanRoute
  '/usp/kegiatan': typeof AppUspKegiatanRoute
  '/usp/pinjaman': typeof AppUspPinjamanRoute
  '/usp/transfer': typeof AppUspTransferRoute
  '/pengaturan': typeof AppPengaturanIndexRoute
  '/usp': typeof AppUspIndexRoute
  '/usp/laporan/laba-rugi': typeof AppUspLaporanLabaRugiRoute
  '/usp/laporan/neraca': typeof AppUspLaporanNeracaRoute
  '/usp/laporan/rekonsiliasi-rk': typeof AppUspLaporanRekonsiliasiRkRoute
  '/usp/laporan': typeof AppUspLaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_app/catat-kegiatan': typeof AppCatatKegiatanRoute
  '/_app/coa': typeof AppCoaRoute
  '/_app/pengaturan': typeof AppPengaturanRouteWithChildren
  '/_app/transfer-antar-entitas': typeof AppTransferAntarEntitasRoute
  '/_app/usp': typeof AppUspRouteWithChildren
  '/login/$unit': typeof LoginUnitRoute
  '/_app/': typeof AppIndexRoute
  '/_app/laporan/bagi-hasil': typeof AppLaporanBagiHasilRoute
  '/_app/laporan/laba-rugi': typeof AppLaporanLabaRugiRoute
  '/_app/laporan/neraca-konsolidasi': typeof AppLaporanNeracaKonsolidasiRoute
  '/_app/laporan/neraca-pusat': typeof AppLaporanNeracaPusatRoute
  '/_app/laporan/rekonsiliasi-rk': typeof AppLaporanRekonsiliasiRkRoute
  '/_app/pengaturan/users': typeof AppPengaturanUsersRoute
  '/_app/pusat/kegiatan': typeof AppPusatKegiatanRoute
  '/_app/usp/kegiatan': typeof AppUspKegiatanRoute
  '/_app/usp/laporan': typeof AppUspLaporanRouteWithChildren
  '/_app/usp/pinjaman': typeof AppUspPinjamanRoute
  '/_app/usp/transfer': typeof AppUspTransferRoute
  '/_app/pengaturan/': typeof AppPengaturanIndexRoute
  '/_app/usp/': typeof AppUspIndexRoute
  '/_app/usp/laporan/laba-rugi': typeof AppUspLaporanLabaRugiRoute
  '/_app/usp/laporan/neraca': typeof AppUspLaporanNeracaRoute
  '/_app/usp/laporan/rekonsiliasi-rk': typeof AppUspLaporanRekonsiliasiRkRoute
  '/_app/usp/laporan/': typeof AppUspLaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catat-kegiatan'
    | '/coa'
    | '/pengaturan'
    | '/transfer-antar-entitas'
    | '/usp'
    | '/login/$unit'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/laporan/rekonsiliasi-rk'
    | '/pengaturan/users'
    | '/pusat/kegiatan'
    | '/usp/kegiatan'
    | '/usp/laporan'
    | '/usp/pinjaman'
    | '/usp/transfer'
    | '/pengaturan/'
    | '/usp/'
    | '/usp/laporan/laba-rugi'
    | '/usp/laporan/neraca'
    | '/usp/laporan/rekonsiliasi-rk'
    | '/usp/laporan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/catat-kegiatan'
    | '/coa'
    | '/transfer-antar-entitas'
    | '/login/$unit'
    | '/'
    | '/laporan/bagi-hasil'
    | '/laporan/laba-rugi'
    | '/laporan/neraca-konsolidasi'
    | '/laporan/neraca-pusat'
    | '/laporan/rekonsiliasi-rk'
    | '/pengaturan/users'
    | '/pusat/kegiatan'
    | '/usp/kegiatan'
    | '/usp/pinjaman'
    | '/usp/transfer'
    | '/pengaturan'
    | '/usp'
    | '/usp/laporan/laba-rugi'
    | '/usp/laporan/neraca'
    | '/usp/laporan/rekonsiliasi-rk'
    | '/usp/laporan'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/catat-kegiatan'
    | '/_app/coa'
    | '/_app/pengaturan'
    | '/_app/transfer-antar-entitas'
    | '/_app/usp'
    | '/login/$unit'
    | '/_app/'
    | '/_app/laporan/bagi-hasil'
    | '/_app/laporan/laba-rugi'
    | '/_app/laporan/neraca-konsolidasi'
    | '/_app/laporan/neraca-pusat'
    | '/_app/laporan/rekonsiliasi-rk'
    | '/_app/pengaturan/users'
    | '/_app/pusat/kegiatan'
    | '/_app/usp/kegiatan'
    | '/_app/usp/laporan'
    | '/_app/usp/pinjaman'
    | '/_app/usp/transfer'
    | '/_app/pengaturan/'
    | '/_app/usp/'
    | '/_app/usp/laporan/laba-rugi'
    | '/_app/usp/laporan/neraca'
    | '/_app/usp/laporan/rekonsiliasi-rk'
    | '/_app/usp/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/login/$unit': {
      id: '/login/$unit'
      path: '/$unit'
      fullPath: '/login/$unit'
      preLoaderRoute: typeof LoginUnitRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_app/usp': {
      id: '/_app/usp'
      path: '/usp'
      fullPath: '/usp'
      preLoaderRoute: typeof AppUspRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer-antar-entitas': {
      id: '/_app/transfer-antar-entitas'
      path: '/transfer-antar-entitas'
      fullPath: '/transfer-antar-entitas'
      preLoaderRoute: typeof AppTransferAntarEntitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coa': {
      id: '/_app/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof AppCoaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catat-kegiatan': {
      id: '/_app/catat-kegiatan'
      path: '/catat-kegiatan'
      fullPath: '/catat-kegiatan'
      preLoaderRoute: typeof AppCatatKegiatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usp/': {
      id: '/_app/usp/'
      path: '/'
      fullPath: '/usp/'
      preLoaderRoute: typeof AppUspIndexRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/pengaturan/': {
      id: '/_app/pengaturan/'
      path: '/'
      fullPath: '/pengaturan/'
      preLoaderRoute: typeof AppPengaturanIndexRouteImport
      parentRoute: typeof AppPengaturanRoute
    }
    '/_app/usp/transfer': {
      id: '/_app/usp/transfer'
      path: '/transfer'
      fullPath: '/usp/transfer'
      preLoaderRoute: typeof AppUspTransferRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/pinjaman': {
      id: '/_app/usp/pinjaman'
      path: '/pinjaman'
      fullPath: '/usp/pinjaman'
      preLoaderRoute: typeof AppUspPinjamanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/laporan': {
      id: '/_app/usp/laporan'
      path: '/laporan'
      fullPath: '/usp/laporan'
      preLoaderRoute: typeof AppUspLaporanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/usp/kegiatan': {
      id: '/_app/usp/kegiatan'
      path: '/kegiatan'
      fullPath: '/usp/kegiatan'
      preLoaderRoute: typeof AppUspKegiatanRouteImport
      parentRoute: typeof AppUspRoute
    }
    '/_app/pusat/kegiatan': {
      id: '/_app/pusat/kegiatan'
      path: '/pusat/kegiatan'
      fullPath: '/pusat/kegiatan'
      preLoaderRoute: typeof AppPusatKegiatanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan/users': {
      id: '/_app/pengaturan/users'
      path: '/users'
      fullPath: '/pengaturan/users'
      preLoaderRoute: typeof AppPengaturanUsersRouteImport
      parentRoute: typeof AppPengaturanRoute
    }
    '/_app/laporan/rekonsiliasi-rk': {
      id: '/_app/laporan/rekonsiliasi-rk'
      path: '/laporan/rekonsiliasi-rk'
      fullPath: '/laporan/rekonsiliasi-rk'
      preLoaderRoute: typeof AppLaporanRekonsiliasiRkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/neraca-pusat': {
      id: '/_app/laporan/neraca-pusat'
      path: '/laporan/neraca-pusat'
      fullPath: '/laporan/neraca-pusat'
      preLoaderRoute: typeof AppLaporanNeracaPusatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/neraca-konsolidasi': {
      id: '/_app/laporan/neraca-konsolidasi'
      path: '/laporan/neraca-konsolidasi'
      fullPath: '/laporan/neraca-konsolidasi'
      preLoaderRoute: typeof AppLaporanNeracaKonsolidasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/laba-rugi': {
      id: '/_app/laporan/laba-rugi'
      path: '/laporan/laba-rugi'
      fullPath: '/laporan/laba-rugi'
      preLoaderRoute: typeof AppLaporanLabaRugiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/laporan/bagi-hasil': {
      id: '/_app/laporan/bagi-hasil'
      path: '/laporan/bagi-hasil'
      fullPath: '/laporan/bagi-hasil'
      preLoaderRoute: typeof AppLaporanBagiHasilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usp/laporan/': {
      id: '/_app/usp/laporan/'
      path: '/'
      fullPath: '/usp/laporan/'
      preLoaderRoute: typeof AppUspLaporanIndexRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/rekonsiliasi-rk': {
      id: '/_app/usp/laporan/rekonsiliasi-rk'
      path: '/rekonsiliasi-rk'
      fullPath: '/usp/laporan/rekonsiliasi-rk'
      preLoaderRoute: typeof AppUspLaporanRekonsiliasiRkRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/neraca': {
      id: '/_app/usp/laporan/neraca'
      path: '/neraca'
      fullPath: '/usp/laporan/neraca'
      preLoaderRoute: typeof AppUspLaporanNeracaRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
    '/_app/usp/laporan/laba-rugi': {
      id: '/_app/usp/laporan/laba-rugi'
      path: '/laba-rugi'
      fullPath: '/usp/laporan/laba-rugi'
      preLoaderRoute: typeof AppUspLaporanLabaRugiRouteImport
      parentRoute: typeof AppUspLaporanRoute
    }
  }
}

interface AppPengaturanRouteChildren {
  AppPengaturanUsersRoute: typeof AppPengaturanUsersRoute
  AppPengaturanIndexRoute: typeof AppPengaturanIndexRoute
}

const AppPengaturanRouteChildren: AppPengaturanRouteChildren = {
  AppPengaturanUsersRoute: AppPengaturanUsersRoute,
  AppPengaturanIndexRoute: AppPengaturanIndexRoute,
}

const AppPengaturanRouteWithChildren = AppPengaturanRoute._addFileChildren(
  AppPengaturanRouteChildren,
)

interface AppUspLaporanRouteChildren {
  AppUspLaporanLabaRugiRoute: typeof AppUspLaporanLabaRugiRoute
  AppUspLaporanNeracaRoute: typeof AppUspLaporanNeracaRoute
  AppUspLaporanRekonsiliasiRkRoute: typeof AppUspLaporanRekonsiliasiRkRoute
  AppUspLaporanIndexRoute: typeof AppUspLaporanIndexRoute
}

const AppUspLaporanRouteChildren: AppUspLaporanRouteChildren = {
  AppUspLaporanLabaRugiRoute: AppUspLaporanLabaRugiRoute,
  AppUspLaporanNeracaRoute: AppUspLaporanNeracaRoute,
  AppUspLaporanRekonsiliasiRkRoute: AppUspLaporanRekonsiliasiRkRoute,
  AppUspLaporanIndexRoute: AppUspLaporanIndexRoute,
}

const AppUspLaporanRouteWithChildren = AppUspLaporanRoute._addFileChildren(
  AppUspLaporanRouteChildren,
)

interface AppUspRouteChildren {
  AppUspKegiatanRoute: typeof AppUspKegiatanRoute
  AppUspLaporanRoute: typeof AppUspLaporanRouteWithChildren
  AppUspPinjamanRoute: typeof AppUspPinjamanRoute
  AppUspTransferRoute: typeof AppUspTransferRoute
  AppUspIndexRoute: typeof AppUspIndexRoute
}

const AppUspRouteChildren: AppUspRouteChildren = {
  AppUspKegiatanRoute: AppUspKegiatanRoute,
  AppUspLaporanRoute: AppUspLaporanRouteWithChildren,
  AppUspPinjamanRoute: AppUspPinjamanRoute,
  AppUspTransferRoute: AppUspTransferRoute,
  AppUspIndexRoute: AppUspIndexRoute,
}

const AppUspRouteWithChildren =
  AppUspRoute._addFileChildren(AppUspRouteChildren)

interface AppRouteChildren {
  AppCatatKegiatanRoute: typeof AppCatatKegiatanRoute
  AppCoaRoute: typeof AppCoaRoute
  AppPengaturanRoute: typeof AppPengaturanRouteWithChildren
  AppTransferAntarEntitasRoute: typeof AppTransferAntarEntitasRoute
  AppUspRoute: typeof AppUspRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLaporanBagiHasilRoute: typeof AppLaporanBagiHasilRoute
  AppLaporanLabaRugiRoute: typeof AppLaporanLabaRugiRoute
  AppLaporanNeracaKonsolidasiRoute: typeof AppLaporanNeracaKonsolidasiRoute
  AppLaporanNeracaPusatRoute: typeof AppLaporanNeracaPusatRoute
  AppLaporanRekonsiliasiRkRoute: typeof AppLaporanRekonsiliasiRkRoute
  AppPusatKegiatanRoute: typeof AppPusatKegiatanRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatatKegiatanRoute: AppCatatKegiatanRoute,
  AppCoaRoute: AppCoaRoute,
  AppPengaturanRoute: AppPengaturanRouteWithChildren,
  AppTransferAntarEntitasRoute: AppTransferAntarEntitasRoute,
  AppUspRoute: AppUspRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLaporanBagiHasilRoute: AppLaporanBagiHasilRoute,
  AppLaporanLabaRugiRoute: AppLaporanLabaRugiRoute,
  AppLaporanNeracaKonsolidasiRoute: AppLaporanNeracaKonsolidasiRoute,
  AppLaporanNeracaPusatRoute: AppLaporanNeracaPusatRoute,
  AppLaporanRekonsiliasiRkRoute: AppLaporanRekonsiliasiRkRoute,
  AppPusatKegiatanRoute: AppPusatKegiatanRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginUnitRoute: typeof LoginUnitRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginUnitRoute: LoginUnitRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
